// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://thlwklykssfpapqtxpkq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRobHdrbHlrc3NmcGFwcXR4cGtxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NDExMTMsImV4cCI6MjA2OTAxNzExM30.-9jPJ5MVb8SFx5h1sATPPLwhu0az3HQEV25X-EXrHRo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
        // storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
    }
});